export const ALL_COMPANY_REQUEST = "ALL_COMPANY_REQUEST";
export const ALL_COMPANY_SUCCESS = "ALL_COMPANY_SUCCESS";
export const ALL_COMPANY_FAIL = "ALL_COMPANY_FAIL";

export const COMPANY_DETAIL_REQUEST = "COMPANY_DETAIL_REQUEST";
export const COMPANY_DETAIL_SUCCESS = "COMPANY_DETAIL_SUCCESS";
export const COMPANY_DETAIL_FAIL = "COMPANY_DETAIL_FAIL";

export const REGISTER_COMPANY_REQUEST = "REGISTER_COMPANY_REQUEST";
export const REGISTER_COMPANY_SUCCESS = "REGISTER_COMPANY_SUCCESS";
export const REGISTER_COMPANY_FAIL = "REGISTER_COMPANY_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

