export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAIL = "CREATE_ORDER_FAIL";

export const COMPANY_ORDER_REQUEST = "COMPANY_ORDER_REQUEST";
export const COMPANY_ORDER_SUCCESS = "COMPANY_ORDER_SUCCESS";
export const COMPANY_ORDER_FAIL = "COMPANY_ORDER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
